In [1]:
# documentation: https://www.selenium.dev/selenium/docs/api/py/webdriver/selenium.webdriver.common.by.html
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
#from selenium.webdriver.common.by import By
import pandas as pd

In [2]:
#!pip install selenium

In [3]:
website = 'https://www.thebalancemoney.com/unemployment-rate-by-year-3305506'

In [4]:
service = Service()
options = webdriver.ChromeOptions()
driver = webdriver.Chrome(service=service, options=options)

In [5]:
driver.get(website)

In [6]:
# XPath for buttons, as applicable //tagName[@AttributeName='Value']
#xpath = ...
#button = driver.find_element_by_xpath(xpath)
#button.click()

In [7]:
data = driver.find_elements('tag name', 'tr') #can also use 'tag name'

In [8]:
for datum in data:
    print(datum.text)
    print(datum.text.split(" "))

YEAR UNEMPLOYMENT RATE (DECEMBER) ANNUAL GDP GROWTH INFLATION (DECEMBER, YOY) NOTABLE EVENTS
['YEAR', 'UNEMPLOYMENT', 'RATE', '(DECEMBER)', 'ANNUAL', 'GDP', 'GROWTH', 'INFLATION', '(DECEMBER,', 'YOY)', 'NOTABLE', 'EVENTS']
1929 3.2% NA 0.6% Market crash
['1929', '3.2%', 'NA', '0.6%', 'Market', 'crash']
1930 8.7% -8.5% -6.4% Smoot-Hawley
['1930', '8.7%', '-8.5%', '-6.4%', 'Smoot-Hawley']
1931 15.9% -6.4% -9.3% Dust Bowl
['1931', '15.9%', '-6.4%', '-9.3%', 'Dust', 'Bowl']
1932 23.6% -12.9% -10.3% Hoover's tax hikes
['1932', '23.6%', '-12.9%', '-10.3%', "Hoover's", 'tax', 'hikes']
1933 24.9% -1.2% 0.8% FDR's New Deal
['1933', '24.9%', '-1.2%', '0.8%', "FDR's", 'New', 'Deal']
1934 21.7% 10.8% 1.5% Depression eased, thanks to New Deal
['1934', '21.7%', '10.8%', '1.5%', 'Depression', 'eased,', 'thanks', 'to', 'New', 'Deal']
1935 20.1% 8.9% 3.0%
['1935', '20.1%', '8.9%', '3.0%', '', '']
1936 16.9% 12.9% 1.4%
['1936', '16.9%', '12.9%', '1.4%', '', '']
1937 14.3% 5.1% 2.9% Spending cuts
['1937', '14.3%', '5.1%', '2.9%', 'Spending', 'cuts']
1938 19.0% -3.3% -2.8% FLSA starts minimum wage
['1938', '19.0%', '-3.3%', '-2.8%', 'FLSA', 'starts', 'minimum', 'wage']
1939 17.2% 8.0% 0% Drought ended
['1939', '17.2%', '8.0%', '0%', 'Drought', 'ended']
1940 14.6% 8.8% 0.7% U.S. draft
['1940', '14.6%', '8.8%', '0.7%', 'U.S.', 'draft']
1941 9.9% 17.7% 9.9% Pearl Harbor
['1941', '9.9%', '17.7%', '9.9%', 'Pearl', 'Harbor']
1942 4.7% 18.9% 9.0% Defense spending tripled
['1942', '4.7%', '18.9%', '9.0%', 'Defense', 'spending', 'tripled']
1943 1.9% 17.0% 3.0% Germany surrendered at Stalingrad
['1943', '1.9%', '17.0%', '3.0%', 'Germany', 'surrendered', 'at', 'Stalingrad']
1944 1.2% 8.0% 2.3% Bretton Woods
['1944', '1.2%', '8.0%', '2.3%', 'Bretton', 'Woods']
1945 1.9% -1.0% 2.2% War ends. Min wage $0.40
['1945', '1.9%', '-1.0%', '2.2%', 'War', 'ends.', 'Min', 'wage', '$0.40']
1946 3.9% -11.6% 18.1% Employment Act
['1946', '3.9%', '-11.6%', '18.1%', 'Employment', 'Act']
1947 3.6% -1.1% 8.8% Marshall Plan negotiated
['1947', '3.6%', '-1.1%', '8.8%', 'Marshall', 'Plan', 'negotiated']
1948 4.0% 4.1% 3.0% Truman re-elected
['1948', '4.0%', '4.1%', '3.0%', 'Truman', 're-elected']
1949 6.6% -0.6% -2.1% Fair Deal; NATO
['1949', '6.6%', '-0.6%', '-2.1%', 'Fair', 'Deal;', 'NATO']
1950 4.3% 8.7% 5.9% Korean War; Min wage $0.75
['1950', '4.3%', '8.7%', '5.9%', 'Korean', 'War;', 'Min', 'wage', '$0.75']
1951 3.1% 8.0% 6.0% Expansion
['1951', '3.1%', '8.0%', '6.0%', 'Expansion']
1952 2.7% 4.1% 0.8% Expansion
['1952', '2.7%', '4.1%', '0.8%', 'Expansion']
1953 4.5% 4.7% 0.7% Korean War ended
['1953', '4.5%', '4.7%', '0.7%', 'Korean', 'War', 'ended']
1954 5.0% -0.6% -0.7% Dow returned to 1929 level
['1954', '5.0%', '-0.6%', '-0.7%', 'Dow', 'returned', 'to', '1929', 'level']
1955 4.2% 7.1% 0.4% Unemployment fell
['1955', '4.2%', '7.1%', '0.4%', 'Unemployment', 'fell']
1956 4.2% 2.1% 3.0% Minimum wage $1.00
['1956', '4.2%', '2.1%', '3.0%', 'Minimum', 'wage', '$1.00']
1957 5.2% 2.1% 2.9% Recession
['1957', '5.2%', '2.1%', '2.9%', 'Recession']
1958 6.2% -0.7% 1.8%
['1958', '6.2%', '-0.7%', '1.8%', '', '']
1959 5.3% 6.9% 1.7% Expansion
['1959', '5.3%', '6.9%', '1.7%', 'Expansion']
1960 6.6% 2.6% 1.4% Recession
['1960', '6.6%', '2.6%', '1.4%', 'Recession']
1961 6.0% 2.6% 0.7% JFK; Min wage $1.15
['1961', '6.0%', '2.6%', '0.7%', 'JFK;', 'Min', 'wage', '$1.15']
1962 5.5% 6.1% 1.3% Cuban Missile Crisis
['1962', '5.5%', '6.1%', '1.3%', 'Cuban', 'Missile', 'Crisis']
1963 5.5% 4.4% 1.6% LBJ; Min wage $1.25
['1963', '5.5%', '4.4%', '1.6%', 'LBJ;', 'Min', 'wage', '$1.25']
1964 5.0% 5.8% 1.0% Tax cut
['1964', '5.0%', '5.8%', '1.0%', 'Tax', 'cut']
1965 4.0% 6.5% 1.9% U.S. enters Vietnam War
['1965', '4.0%', '6.5%', '1.9%', 'U.S.', 'enters', 'Vietnam', 'War']
1966 3.8% 6.6% 3.5% Expansion
['1966', '3.8%', '6.6%', '3.5%', 'Expansion']
1967 3.8% 2.7% 3.0% Min wage $1.40
['1967', '3.8%', '2.7%', '3.0%', 'Min', 'wage', '$1.40']
1968 3.4% 4.9% 4.7% Min wage $1.60
['1968', '3.4%', '4.9%', '4.7%', 'Min', 'wage', '$1.60']
1969 3.5% 3.1% 6.2% Nixon took office
['1969', '3.5%', '3.1%', '6.2%', 'Nixon', 'took', 'office']
1970 6.1% 0.2% 5.6% Recession
['1970', '6.1%', '0.2%', '5.6%', 'Recession']
1971 6.0% 3.3% 3.3% Emergency Employment Act; Wage-price controls
['1971', '6.0%', '3.3%', '3.3%', 'Emergency', 'Employment', 'Act;', 'Wage-price', 'controls']
1972 5.2% 5.3% 3.4% Ongoing Stagflation; Watergate break-in
['1972', '5.2%', '5.3%', '3.4%', 'Ongoing', 'Stagflation;', 'Watergate', 'break-in']
1973 4.9% 5.6% 8.7% CETA ; Gold standard ;  Vietnam War ended
['1973', '4.9%', '5.6%', '8.7%', 'CETA', ';', 'Gold', 'standard', ';', '', 'Vietnam', 'War', 'ended']
1974 7.2% -0.5% 12.3% Nixon resigns; Min. wage $2.00
['1974', '7.2%', '-0.5%', '12.3%', 'Nixon', 'resigns;', 'Min.', 'wage', '$2.00']
1975 8.2% -0.2% 6.9% Recession ended
['1975', '8.2%', '-0.2%', '6.9%', 'Recession', 'ended']
1976 7.8% 5.4% 4.9% Expansion
['1976', '7.8%', '5.4%', '4.9%', 'Expansion']
1977 6.4% 4.6% 6.7% Carter took office
['1977', '6.4%', '4.6%', '6.7%', 'Carter', 'took', 'office']
1978 6.0% 5.5% 9.0% Fed raised rate to 20% to stop inflation
['1978', '6.0%', '5.5%', '9.0%', 'Fed', 'raised', 'rate', 'to', '20%', 'to', 'stop', 'inflation']
1979 6.0% 3.2% 13.3%
['1979', '6.0%', '3.2%', '13.3%', '', '']
1980 7.2% -0.3% 12.5% Recession
['1980', '7.2%', '-0.3%', '12.5%', 'Recession']
1981 8.5% 2.5% 8.9% Reagan tax cuts; Min. wage $3.35
['1981', '8.5%', '2.5%', '8.9%', 'Reagan', 'tax', 'cuts;', 'Min.', 'wage', '$3.35']
1982 10.8% -1.8% 3.8% Job Training Partnership Act;   Garn-St.Germain Act
['1982', '10.8%', '-1.8%', '3.8%', 'Job', 'Training', 'Partnership', 'Act;', '', '', 'Garn-St.Germain', 'Act']
1983 8.3% 4.6% 3.8% Reagan increased military spending
['1983', '8.3%', '4.6%', '3.8%', 'Reagan', 'increased', 'military', 'spending']
1984 7.3% 7.2% 3.9%
['1984', '7.3%', '7.2%', '3.9%', '', '']
1985 7.0% 4.2% 3.8% Expansion
['1985', '7.0%', '4.2%', '3.8%', 'Expansion']
1986 6.6% 3.5% 1.1% Tax cuts
['1986', '6.6%', '3.5%', '1.1%', 'Tax', 'cuts']
1987 5.7% 3.5% 4.4% Black Monday
['1987', '5.7%', '3.5%', '4.4%', 'Black', 'Monday']
1988 5.3% 4.2% 4.4% Fed raised rate
['1988', '5.3%', '4.2%', '4.4%', 'Fed', 'raised', 'rate']
1989 5.4% 3.7% 4.6% Reforms made to address S&L Crisis
['1989', '5.4%', '3.7%', '4.6%', 'Reforms', 'made', 'to', 'address', 'S&L', 'Crisis']
1990 6.3% 1.9% 6.1% Recession
['1990', '6.3%', '1.9%', '6.1%', 'Recession']
1991 7.3% -0.1% 3.1% Desert Storm; Min. wage $4.25
['1991', '7.3%', '-0.1%', '3.1%', 'Desert', 'Storm;', 'Min.', 'wage', '$4.25']
1992 7.4% 3.5% 2.9% NAFTA drafted
['1992', '7.4%', '3.5%', '2.9%', 'NAFTA', 'drafted']
1993 6.5% 2.8% 2.7% Omnibus Budget Reconciliation Act
['1993', '6.5%', '2.8%', '2.7%', 'Omnibus', 'Budget', 'Reconciliation', 'Act']
1994 5.5% 4.0% 2.7% School to Work Act
['1994', '5.5%', '4.0%', '2.7%', 'School', 'to', 'Work', 'Act', '']
1995 5.6% 2.7% 2.5% Expansion
['1995', '5.6%', '2.7%', '2.5%', 'Expansion']
1996 5.4% 3.8% 3.3% Welfare reform
['1996', '5.4%', '3.8%', '3.3%', 'Welfare', 'reform']
1997 4.7% 4.4% 1.7% Min. wage $5.85
['1997', '4.7%', '4.4%', '1.7%', 'Min.', 'wage', '$5.85']
1998 4.4% 4.5% 1.6% LTCM crisis
['1998', '4.4%', '4.5%', '1.6%', 'LTCM', 'crisis']
1999 4.0% 4.8% 2.7% Euro; Serbian airstrike
['1999', '4.0%', '4.8%', '2.7%', 'Euro;', 'Serbian', 'airstrike']
2000 3.9% 4.1% 3.4% NASDAQ hit record high
['2000', '3.9%', '4.1%', '3.4%', 'NASDAQ', 'hit', 'record', 'high']
2001 5.7% 1.0% 1.6% Bush tax cuts; 9/11 attacks
['2001', '5.7%', '1.0%', '1.6%', 'Bush', 'tax', 'cuts;', '9/11', 'attacks']
2002 6.0% 1.7% 2.4% War on Terror
['2002', '6.0%', '1.7%', '2.4%', 'War', 'on', 'Terror']
2003 5.7% 2.8% 1.9% JGTRRA
['2003', '5.7%', '2.8%', '1.9%', 'JGTRRA']
2004 5.4% 3.9% 3.3% Expansion
['2004', '5.4%', '3.9%', '3.3%', 'Expansion']
2005 4.9% 3.5% 3.4% Bankruptcy Abuse Prevention Act; Katrina
['2005', '4.9%', '3.5%', '3.4%', 'Bankruptcy', 'Abuse', 'Prevention', 'Act;', 'Katrina']
2006 4.4% 2.8% 2.5% Expansion
['2006', '4.4%', '2.8%', '2.5%', 'Expansion']
2007 5.0% 2.0% 4.1%
['2007', '5.0%', '2.0%', '4.1%', '', '']
2008 7.3% 0.1% 0.1% Min. wage $6.55; Financial crisis
['2008', '7.3%', '0.1%', '0.1%', 'Min.', 'wage', '$6.55;', 'Financial', 'crisis']
2009 9.9% -2.6% 2.7% ARRA; Minimum wage $7.25; Jobless benefits extended
['2009', '9.9%', '-2.6%', '2.7%', 'ARRA;', 'Minimum', 'wage', '$7.25;', 'Jobless', 'benefits', 'extended']

2010 9.3% 2.7% 1.5% Obama tax cuts
['2010', '9.3%', '2.7%', '1.5%', 'Obama', 'tax', 'cuts']
2011 8.5% 1.5% 3.0% 26 months of job losses by July; Debt ceiling crisis; Iraq War ended
['2011', '8.5%', '1.5%', '3.0%', '26', 'months', 'of', 'job', 'losses', 'by', 'July;', 'Debt', 'ceiling', 'crisis;', 'Iraq', 'War', 'ended']
2012 7.9% 2.3% 1.7% QE; 10-year rate at 200-year low; Fiscal cliff
['2012', '7.9%', '2.3%', '1.7%', 'QE;', '10-year', 'rate', 'at', '200-year', 'low;', 'Fiscal', 'cliff']
2013 6.7% 1.8% 1.5% Stocks up 30%; Long term = 5% unemployment
['2013', '6.7%', '1.8%', '1.5%', 'Stocks', 'up', '30%;', 'Long', 'term', '=', '5%', 'unemployment']
2014 5.6% 2.3% 0.8% Unemployment at 2007 levels
['2014', '5.6%', '2.3%', '0.8%', 'Unemployment', 'at', '2007', 'levels']
2015 5.0% 2.7% 0.7% Natural rate
['2015', '5.0%', '2.7%', '0.7%', 'Natural', 'rate']
2016 4.7% 1.7% 2.1% Presidential race
['2016', '4.7%', '1.7%', '2.1%', 'Presidential', 'race']
2017 4.1% 2.3% 2.1% Dollar weakened
['2017', '4.1%', '2.3%', '2.1%', 'Dollar', 'weakened']
2018 3.9% 2.9% 1.9% Trump tax cuts
['2018', '3.9%', '2.9%', '1.9%', 'Trump', 'tax', 'cuts']
2019 3.6% 2.3% 2.3% Goldilocks economy
['2019', '3.6%', '2.3%', '2.3%', 'Goldilocks', 'economy']
2020 6.7% -3.4% 1.4% COVID-19 pandemic and recession
['2020', '6.7%', '-3.4%', '1.4%', 'COVID-19', 'pandemic', 'and', 'recession']
2021 3.9% 5.7% 7.0% COVID-19 pandemic and recovery
['2021', '3.9%', '5.7%', '7.0%', 'COVID-19', 'pandemic', 'and', 'recovery']

In [9]:
year = []
unemployment_rate = []
annual_gdp_growth = []
inflation_rate = []
notable_events = []

In [10]:
for i in range(1, len(data)):
    datum = data[i]
    lst_datum = datum.text.split(" ")
    year.append(lst_datum[0])
    unemployment_rate.append(lst_datum[1])
    annual_gdp_growth.append(lst_datum[2])
    inflation_rate.append(lst_datum[3])
    notable_events.append(' '.join(lst_datum[4:]))

In [11]:
dict_data = {"year": year, "unemployment_rate": unemployment_rate, "annual_gdp_growth": annual_gdp_growth,
             "inflation_rate": inflation_rate, "notable_events": notable_events}

In [12]:
dict_data

{'year': ['1929',
  '1930',
  '1931',
  '1932',
  '1933',
  '1934',
  '1935',
  '1936',
  '1937',
  '1938',
  '1939',
  '1940',
  '1941',
  '1942',
  '1943',
  '1944',
  '1945',
  '1946',
  '1947',
  '1948',
  '1949',
  '1950',
  '1951',
  '1952',
  '1953',
  '1954',
  '1955',
  '1956',
  '1957',
  '1958',
  '1959',
  '1960',
  '1961',
  '1962',
  '1963',
  '1964',
  '1965',
  '1966',
  '1967',
  '1968',
  '1969',
  '1970',
  '1971',
  '1972',
  '1973',
  '1974',
  '1975',
  '1976',
  '1977',
  '1978',
  '1979',
  '1980',
  '1981',
  '1982',
  '1983',
  '1984',
  '1985',
  '1986',
  '1987',
  '1988',
  '1989',
  '1990',
  '1991',
  '1992',
  '1993',
  '1994',
  '1995',
  '1996',
  '1997',
  '1998',
  '1999',
  '2000',
  '2001',
  '2002',
  '2003',
  '2004',
  '2005',
  '2006',
  '2007',
  '2008',
  '2009',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021'],
 'unemployment_rate': ['3.2%',
  '8.7%',
  '15.9%',
  '23.6%',
  '24.9%',
  '21.7%',
  '20.1%',
  '16.9%',
  '14.3%',
  '19.0%',
  '17.2%',
  '14.6%',
  '9.9%',
  '4.7%',
  '1.9%',
  '1.2%',
  '1.9%',
  '3.9%',
  '3.6%',
  '4.0%',
  '6.6%',
  '4.3%',
  '3.1%',
  '2.7%',
  '4.5%',
  '5.0%',
  '4.2%',
  '4.2%',
  '5.2%',
  '6.2%',
  '5.3%',
  '6.6%',
  '6.0%',
  '5.5%',
  '5.5%',
  '5.0%',
  '4.0%',
  '3.8%',
  '3.8%',
  '3.4%',
  '3.5%',
  '6.1%',
  '6.0%',
  '5.2%',
  '4.9%',
  '7.2%',
  '8.2%',
  '7.8%',
  '6.4%',
  '6.0%',
  '6.0%',
  '7.2%',
  '8.5%',
  '10.8%',
  '8.3%',
  '7.3%',
  '7.0%',
  '6.6%',
  '5.7%',
  '5.3%',
  '5.4%',
  '6.3%',
  '7.3%',
  '7.4%',
  '6.5%',
  '5.5%',
  '5.6%',
  '5.4%',
  '4.7%',
  '4.4%',
  '4.0%',
  '3.9%',
  '5.7%',
  '6.0%',
  '5.7%',
  '5.4%',
  '4.9%',
  '4.4%',
  '5.0%',
  '7.3%',
  '9.9%',
  '9.3%',
  '8.5%',
  '7.9%',
  '6.7%',
  '5.6%',
  '5.0%',
  '4.7%',
  '4.1%',
  '3.9%',
  '3.6%',
  '6.7%',
  '3.9%'],
 'annual_gdp_growth': ['NA',
  '-8.5%',
  '-6.4%',
  '-12.9%',
  '-1.2%',
  '10.8%',
  '8.9%',
  '12.9%',
  '5.1%',
  '-3.3%',
  '8.0%',
  '8.8%',
  '17.7%',
  '18.9%',
  '17.0%',
  '8.0%',
  '-1.0%',
  '-11.6%',
  '-1.1%',
  '4.1%',
  '-0.6%',
  '8.7%',
  '8.0%',
  '4.1%',
  '4.7%',
  '-0.6%',
  '7.1%',
  '2.1%',
  '2.1%',
  '-0.7%',
  '6.9%',
  '2.6%',
  '2.6%',
  '6.1%',
  '4.4%',
  '5.8%',
  '6.5%',
  '6.6%',
  '2.7%',
  '4.9%',
  '3.1%',
  '0.2%',
  '3.3%',
  '5.3%',
  '5.6%',
  '-0.5%',
  '-0.2%',
  '5.4%',
  '4.6%',
  '5.5%',
  '3.2%',
  '-0.3%',
  '2.5%',
  '-1.8%',
  '4.6%',
  '7.2%',
  '4.2%',
  '3.5%',
  '3.5%',
  '4.2%',
  '3.7%',
  '1.9%',
  '-0.1%',
  '3.5%',
  '2.8%',
  '4.0%',
  '2.7%',
  '3.8%',
  '4.4%',
  '4.5%',
  '4.8%',
  '4.1%',
  '1.0%',
  '1.7%',
  '2.8%',
  '3.9%',
  '3.5%',
  '2.8%',
  '2.0%',
  '0.1%',
  '-2.6%',
  '2.7%',
  '1.5%',
  '2.3%',
  '1.8%',
  '2.3%',
  '2.7%',
  '1.7%',
  '2.3%',
  '2.9%',
  '2.3%',
  '-3.4%',
  '5.7%'],
 'inflation_rate': ['0.6%',
  '-6.4%',
  '-9.3%',
  '-10.3%',
  '0.8%',
  '1.5%',
  '3.0%',
  '1.4%',
  '2.9%',
  '-2.8%',
  '0%',
  '0.7%',
  '9.9%',
  '9.0%',
  '3.0%',
  '2.3%',
  '2.2%',
  '18.1%',
  '8.8%',
  '3.0%',
  '-2.1%',
  '5.9%',
  '6.0%',
  '0.8%',
  '0.7%',
  '-0.7%',
  '0.4%',
  '3.0%',
  '2.9%',
  '1.8%',
  '1.7%',
  '1.4%',
  '0.7%',
  '1.3%',
  '1.6%',
  '1.0%',
  '1.9%',
  '3.5%',
  '3.0%',
  '4.7%',
  '6.2%',
  '5.6%',
  '3.3%',
  '3.4%',
  '8.7%',
  '12.3%',
  '6.9%',
  '4.9%',
  '6.7%',
  '9.0%',
  '13.3%',
  '12.5%',
  '8.9%',
  '3.8%',
  '3.8%',
  '3.9%',
  '3.8%',
  '1.1%',
  '4.4%',
  '4.4%',
  '4.6%',
  '6.1%',
  '3.1%',
  '2.9%',
  '2.7%',
  '2.7%',
  '2.5%',
  '3.3%',
  '1.7%',
  '1.6%',
  '2.7%',
  '3.4%',
  '1.6%',
  '2.4%',
  '1.9%',
  '3.3%',
  '3.4%',
  '2.5%',
  '4.1%',
  '0.1%',
  '2.7%',
  '1.5%',
  '3.0%',
  '1.7%',
  '1.5%',
  '0.8%',
  '0.7%',
  '2.1%',
  '2.1%',
  '1.9%',
  '2.3%',
  '1.4%',
  '7.0%'],
 'notable_events': ['Market crash',
  'Smoot-Hawley',
  'Dust Bowl',
  "Hoover's tax hikes",
  "FDR's New Deal",
  'Depression eased, thanks to New Deal',
  ' ',
  ' ',
  'Spending cuts',
  'FLSA starts minimum wage',
  'Drought ended',
  'U.S. draft',
  'Pearl Harbor',
  'Defense spending tripled',
  'Germany surrendered at Stalingrad',
  'Bretton Woods',
  'War ends. Min wage $0.40',
  'Employment Act',
  'Marshall Plan negotiated',
  'Truman re-elected',
  'Fair Deal; NATO',
  'Korean War; Min wage $0.75',
  'Expansion',
  'Expansion',
  'Korean War ended',
  'Dow returned to 1929 level',
  'Unemployment fell',
  'Minimum wage $1.00',
  'Recession',
  ' ',
  'Expansion',
  'Recession',
  'JFK; Min wage $1.15',
  'Cuban Missile Crisis',
  'LBJ; Min wage $1.25',
  'Tax cut',
  'U.S. enters Vietnam War',
  'Expansion',
  'Min wage $1.40',
  'Min wage $1.60',
  'Nixon took office',
  'Recession',
  'Emergency Employment Act; Wage-price controls',
  'Ongoing Stagflation; Watergate break-in',
  'CETA ; Gold standard ;  Vietnam War ended',
  'Nixon resigns; Min. wage $2.00',
  'Recession ended',
  'Expansion',
  'Carter took office',
  'Fed raised rate to 20% to stop inflation',
  ' ',
  'Recession',
  'Reagan tax cuts; Min. wage $3.35',
  'Job Training Partnership Act;   Garn-St.Germain Act',
  'Reagan increased military spending',
  ' ',
  'Expansion',
  'Tax cuts',
  'Black Monday',
  'Fed raised rate',
  'Reforms made to address S&L Crisis',
  'Recession',
  'Desert Storm; Min. wage $4.25',
  'NAFTA drafted',
  'Omnibus Budget Reconciliation Act',
  'School to Work Act ',
  'Expansion',
  'Welfare reform',
  'Min. wage $5.85',
  'LTCM crisis',
  'Euro; Serbian airstrike',
  'NASDAQ hit record high',
  'Bush tax cuts; 9/11 attacks',
  'War on Terror',
  'JGTRRA',
  'Expansion',
  'Bankruptcy Abuse Prevention Act; Katrina',
  'Expansion',
  ' ',
  'Min. wage $6.55; Financial crisis',
  'ARRA; Minimum wage $7.25; Jobless benefits extended',
  'Obama tax cuts',
  '26 months of job losses by July; Debt ceiling crisis; Iraq War ended',
  'QE; 10-year rate at 200-year low; Fiscal cliff',
  'Stocks up 30%; Long term = 5% unemployment',
  'Unemployment at 2007 levels',
  'Natural rate',
  'Presidential race',
  'Dollar weakened',
  'Trump tax cuts',
  'Goldilocks economy',
  'COVID-19 pandemic and recession',
  'COVID-19 pandemic and recovery']}

In [13]:
df = pd.DataFrame(dict_data)

In [14]:
df

,year,unemployment_rate,annual_gdp_growth,inflation_rate,notable_events
0,1929,3.2%,NA,0.6%,Market crash
1,1930,8.7%,-8.5%,-6.4%,Smoot-Hawley
2,1931,15.9%,-6.4%,-9.3%,Dust Bowl
3,1932,23.6%,-12.9%,-10.3%,Hoover's tax hikes
4,1933,24.9%,-1.2%,0.8%,FDR's New Deal
...,...,...,...,...,...
88,2017,4.1%,2.3%,2.1%,Dollar weakened
89,2018,3.9%,2.9%,1.9%,Trump tax cuts
90,2019,3.6%,2.3%,2.3%,Goldilocks economy
91,2020,6.7%,-3.4%,1.4%,COVID-19 pandemic and recession
92,2021,3.9%,5.7%,7.0%,COVID-19 pandemic and recovery

In [15]:
df['unemployment_rate'] = df.unemployment_rate.apply(lambda x: float(x[:-1])*.01)

In [16]:
df['inflation_rate'] = df.inflation_rate.apply(lambda x: float(x[:-1])*.01)

In [17]:
df[df['annual_gdp_growth'] == "NA"]

   year  unemployment_rate annual_gdp_growth  inflation_rate notable_events
0  1929              0.032                NA           0.006   Market crash

In [18]:
df['annual_gdp_growth'] = df.annual_gdp_growth.apply(lambda x: float('NaN') if x == "NA" else float(x[:-1])*.01)

In [19]:
df['year'] = df['year'].astype(int)

In [20]:
df

,year,unemployment_rate,annual_gdp_growth,inflation_rate,notable_events
0,1929,0.032,NaN,0.006,Market crash
1,1930,0.087,-0.085,-0.064,Smoot-Hawley
2,1931,0.159,-0.064,-0.093,Dust Bowl
3,1932,0.236,-0.129,-0.103,Hoover's tax hikes
4,1933,0.249,-0.012,0.008,FDR's New Deal
...,...,...,...,...,...
88,2017,0.041,0.023,0.021,Dollar weakened
89,2018,0.039,0.029,0.019,Trump tax cuts
90,2019,0.036,0.023,0.023,Goldilocks economy
91,2020,0.067,-0.034,0.014,COVID-19 pandemic and recession
92,2021,0.039,0.057,0.070,COVID-19 pandemic and recovery

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   year               93 non-null     int32
 1   unemployment_rate  93 non-null     float64
 2   annual_gdp_growth  92 non-null     float64
 3   inflation_rate     93 non-null     float64
 4   notable_events     93 non-null     object
dtypes: float64(3), int32(1), object(1)
memory usage: 3.4+ KB

In [22]:
df.to_csv("./economic_data.csv", index=False)

In [23]:
#driver.quit()